cmake_minimum_required(VERSION 3.18.2)
project(my_second_cmake_project)
add_executable(my_second_cmake_program quest_3_9_02.cpp class_Figure.cpp class_Parallelogramm.cpp class_PR_q.cpp class_PR_triangle.cpp class_Quadrilateral.cpp class_RB_triangle.cpp class_Romb.cpp class_RS_triangle.cpp class_Square.cpp class_Triangle.cpp)

